[package]
name = "patin-service-upower"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Optional UPower battery provider for Patin shells"
license.workspace = true
publish.workspace = true

[dependencies]
patin = { path = "../.." }
zbus = { version = "=5.18.0", default-features = false, features = [
    "async-executor",
    "async-fs",
    "async-io",
    "async-lock",
    "async-process",
    "async-task",
    "blocking",
    "blocking-api",
] }
