[package]
name = "patin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "A native Rust toolkit for building Wayland graphical shells"
license.workspace = true
publish.workspace = true

[dependencies]
chrono = { version = "=0.4.45", default-features = false, features = ["clock", "std"] }
cosmic-text = { version = "=0.19.0", default-features = false, features = ["fontconfig", "std", "swash"] }
smithay-client-toolkit = { version = "=0.21.1", default-features = false, features = ["calloop"] }
tiny-skia = { version = "=0.12.0", default-features = false, features = ["std"] }

[dev-dependencies]
patin-service-brightness = { path = "crates/patin-service-brightness" }
patin-service-upower = { path = "crates/patin-service-upower" }
patin-service-volume = { path = "crates/patin-service-volume" }

[workspace]
members = [
    "crates/patin-service-brightness",
    "crates/patin-service-upower",
    "crates/patin-service-volume",
]

[workspace.package]
edition = "2024"
rust-version = "1.97"
license = "MIT"
publish = false
