[package]
name = "patin"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
description = "A native Rust graphical shell for Wayland"
license = "MIT"
publish = false

[[bin]]
name = "patin"
path = "src/main.rs"

[dependencies]
smithay-client-toolkit = { version = "=0.21.1", default-features = false, features = ["calloop"] }
