[package]
name = "patin-login"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "A touch-friendly greetd greeter built on Patin"
license.workspace = true
publish.workspace = true

[dependencies]
chrono = { version = "=0.4.45", default-features = false, features = ["clock", "std"] }
patin = { path = "../.." }
patin-icons = { path = "../patin-icons" }
patin-service-network = { path = "../patin-service-network" }
patin-service-upower = { path = "../patin-service-upower" }
patin-keyboard = { path = "../patin-keyboard" }
serde = { version = "=1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "=1.0.149", default-features = false, features = ["std"] }
zeroize = "=1.9.0"
